### ISSUE TITLE
node version

### ISSUE THREAD

**Issue by rogueturnip** [hlfshell/serial-synapse#1]
Hi!

This looks really great.  I'm wondering, what version of node is this tested on?  I'm trying to run this on an Arduino Yun and the Node version is 0.12.7.

Thanks!

**Comment by hlfshell** [comment]
Hello -

I've used this extensively with node 4+ including 5+.

Arduinos I've used this on successfully are the Arduino Uno, Nano, several of the Adafruit Feathers, and I think it's the Arduino mini.
